# Generated by Django 2.1.7 on 2019-05-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('summary', models.TextField(max_length=1000)),
                ('escalation_policy', models.CharField(max_length=10)),
            ],
        ),
    ]
