language: generic
sudo: required

os:
- linux

env:
  global:
  - SLACK_SIGNING_SECRET:shhdonttellanyone

before_install:
  # Install newer version of Docker, at least 18.03 - this includes `host.docker.internal` DNS address which we rely on
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

  # Also install latest docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

  - docker --version
  - docker-compose --version

jobs:
  include:
  - stage: E2E tests
    script:
    - bash ./e2e/run.sh
