# Generated by Django 2.1.7 on 2019-05-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='impact',
            field=models.TextField(blank=True, help_text='What impact is this having?', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='lead',
            field=models.CharField(blank=True, help_text='Who is leading?', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='summary',
            field=models.TextField(blank=True, help_text="What's the high level summary?", null=True),
        ),
    ]
