# Generated by Django 2.2.2 on 2019-06-17 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190507_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Incident')),
            ],
            options={
                'unique_together': {('incident', 'key')},
            },
        ),
    ]
