# Generated by Django 2.1.7 on 2019-06-12 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190507_2049'),
        ('slack', '0002_auto_20190612_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, default='')),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='incident',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Who is leading?', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead', to='slack.SlackUser'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporter', to='slack.SlackUser'),
        ),
        migrations.AddField(
            model_name='action',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Incident'),
        ),
    ]
