# Generated by Django 2.1.7 on 2019-06-12 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190612_1032'),
        ('slack', '0002_auto_20190612_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack.SlackUser'),
        ),
    ]
