# Generated by Django 2.2.2 on 2019-06-24 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def MoveToExternalID(apps, schema_editor):
    Incident = apps.get_model('core', 'Incident')
    ExternalUser = apps.get_model('core', 'ExternalUser')

    for inc in Incident.objects.all():
        inc.reporter = ExternalUser.objects.get(external_id=inc.reporter_tmp)
        if inc.lead_tmp:
            inc.lead = ExternalUser.objects.get(external_id=inc.lead_tmp)
        inc.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_create_ExternalUser'),
        ('slack','0003_auto_20190624_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='lead',
            new_name='lead_tmp',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='reporter',
            new_name='reporter_tmp',
        ),
        migrations.AddField(
            model_name='incident',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Who is leading?', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead', to='core.ExternalUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporter', to='core.ExternalUser'),
            preserve_default=False,
        ),
        migrations.RunPython(MoveToExternalID),
        migrations.RemoveField(
            model_name='incident',
            name='reporter_tmp',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='lead_tmp',
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, default='')),
                ('done', models.BooleanField(default=False)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Incident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ExternalUser')),
            ],
        ),
    ]
