# Generated by Django 2.1.7 on 2019-04-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=200)),
                ('reporter', models.CharField(default='', max_length=50)),
                ('report_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, help_text="What's the high level summary?")),
                ('impact', models.TextField(blank=True, help_text='What impact is this having?')),
                ('lead', models.CharField(blank=True, help_text='Who is leading?', max_length=50)),
                ('severity', models.CharField(blank=True, choices=[('1', 'critical'), ('2', 'major'), ('3', 'minor'), ('4', 'trivial')], max_length=10, null=True)),
            ],
        ),
    ]
