# Generated by Django 2.2.20 on 2021-04-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("response", "0017_externaluser_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="grafana_annotation_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
