# Generated by Django 2.1.7 on 2019-06-12 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def PopulateSlackUsers(apps, schema_editor):
    SlackUser = apps.get_model('slack', 'SlackUser')
    UserStats = apps.get_model('slack', 'UserStats')

    for userStat in UserStats.objects.all():
        slackUser, created = SlackUser.objects.get_or_create(user_id=userStat.user_id)
        slackUser.save()

    Incidents = apps.get_model('core', 'Incident')
    for inc in Incidents.objects.all():
        if inc.reporter:
            slackUser, created = SlackUser.objects.get_or_create(user_id=inc.reporter)
            slackUser.save()
        if inc.lead:
            slackUser, created = SlackUser.objects.get_or_create(user_id=inc.lead)
            slackUser.save()

    PinnedMessage = apps.get_model('slack', 'pinnedmessage')
    for pm in PinnedMessage.objects.all():
        slackUser, created = SlackUser.objects.get_or_create(user_id=pm.author_id)
        slackUser.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slack', '0001_initial'),
    ]


    operations = [
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(PopulateSlackUsers),
    ]
