# Generated by Django 2.1.7 on 2019-06-12 12:31

from django.db import migrations, models
import django.db.models.deletion


def move_userstats_user_id_forward(apps, schema_editor):
    SlackUser = apps.get_model('slack', 'SlackUser')
    UserStats = apps.get_model('slack', 'UserStats')
    for userStat in UserStats.objects.all():
        user, created = SlackUser.objects.get_or_create(user_id=userStat.user_id_tmp)
        if created:
            user.save()
        userStat.user = user
        userStat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_action_user'),
        ('slack', '0002_auto_20190612_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstats',
            old_name='user_id',
            new_name='user_id_tmp',
        ),
        migrations.AddField(
            model_name='userstats',
            name='user',
            field=models.ForeignKey(default=5555, on_delete=django.db.models.deletion.CASCADE, to='slack.SlackUser'),
            preserve_default=False,
        ),
        migrations.RunPython(move_userstats_user_id_forward),
        migrations.AlterUniqueTogether(
            name='userstats',
            unique_together={('incident', 'user')},
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='user_id_tmp',
        ),
        migrations.AlterField(
            model_name='pinnedmessage',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='slack.SlackUser'),
        ),
    ]
