version: "2"

services:
  response:
    image: response
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - db

  cron:
    image: response
    command: cron
    environment:
      RESPONSE_URL: http://response:8000
    depends_on:
      - response

  db:
    image: postgres:11.2
    ports:
      - 4456:5432
    environment:
      POSTGRES_PASSWORD: response
      POSTGRES_USER: response
      POSTGRES_DB: response
